version: '3'
services:
  php7.0-cli:
    build: docker/php7.0-cli
    volumes:
      - .:/app
    environment:
      - INVOICEFOX_API_KEY
    env_file: .env
  php7.1-cli:
    build: docker/php7.0-cli
    volumes:
      - .:/app
    environment:
      - INVOICEFOX_API_KEY
    env_file: .env
  php7.2-cli:
    build: docker/php7.0-cli
    volumes:
      - .:/app
    environment:
      - INVOICEFOX_API_KEY
    env_file: .env