FROM php:7.0-cli-alpine

RUN cd /usr/local/bin && curl --silent --show-error https://getcomposer.org/installer | php
RUN ln -s /usr/local/bin/composer.phar /usr/local/bin/composer
RUN adduser -D -u 1000 user

ADD . /app

RUN rm -rf /app/composer.lock /app/vendor
RUN chown -R 1000:1000 /app

USER user
WORKDIR /app

CMD /usr/local/bin/composer.phar docker-test