<?php
/**
 * Created by PhpStorm.
 * User: az
 * Date: 22.7.2018
 * Time: 0:49
 */

namespace RTFM\InvoiceFoxAPI\API;


use RTFM\InvoiceFoxAPI\Model\BaseModel;
use RTFM\InvoiceFoxAPI\Model\Invoice;

class InvoicesRepository extends APIResource
{

    protected $resourceName = 'invoice-sent';

    protected $resourceModel = Invoice::class;


    public function list()
    {
        return parent::list();
    }

    public function get(int $id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function delete(int $id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function create(BaseModel $obj)
    {
        return parent::create($obj); // TODO: Change the autogenerated stub
    }

    public function update(BaseModel $obj)
    {
        return parent::update($obj); // TODO: Change the autogenerated stub
    }


}