<?php
/**
 * Created by PhpStorm.
 * User: az
 * Date: 22.7.2018
 * Time: 0:49
 */

namespace RTFM\InvoiceFoxAPI\API;


use RTFM\InvoiceFoxAPI\Model\BaseModel;
use RTFM\InvoiceFoxAPI\Model\Partner;

class PartnersRepository extends APIResource
{

    protected $resourceName = 'partner';

    protected $resourceModel = Partner::class;

    /**
     * @return array
     * @throws \RTFM\InvoiceFoxAPI\Exception\APIException
     * @throws \RTFM\InvoiceFoxAPI\Exception\NotFoundException
     */
    public function list()
    {
        return parent::list(); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     * @return Partner
     * @throws \RTFM\InvoiceFoxAPI\Exception\APIException
     * @throws \RTFM\InvoiceFoxAPI\Exception\NotFoundException
     */
    public function get(int $id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     * @return bool
     * @throws \RTFM\InvoiceFoxAPI\Exception\APIException
     */
    public function delete(int $id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param Partner $obj
     * @return Partner
     * @throws \RTFM\InvoiceFoxAPI\Exception\APIException
     * @throws \RTFM\InvoiceFoxAPI\Exception\NotFoundException
     */
    public function create(BaseModel $obj)
    {
        return parent::create($obj); // TODO: Change the autogenerated stub
    }

    /**
     * @param Partner $obj
     * @return Partner
     * @throws \RTFM\InvoiceFoxAPI\Exception\APIException
     * @throws \RTFM\InvoiceFoxAPI\Exception\NotFoundException
     */
    public function update(BaseModel $obj)
    {
        return parent::update($obj); // TODO: Change the autogenerated stub
    }


}